config/routes.rb
Apitest::Application.routes.draw do
 

  root "countries#index"
  # custom nested route 
  get "countries/:id/download_holidays" => "countries#download_holidays", :as => "country_holiday_download"
 
  resources :countries do 
    resources :holidays
  end

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :holidays 	

	def holiday_downloaded? 
		not download 
	end 
end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  belongs_to :country 

	COUNTRIES = ["US", "Hong Kong", "Australia"]
    
    YEARS = ["2013","2014", "2015"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController




def index 
	@countries = Country.all
  if @countries.present?
  else  
    download_countries
  end 
   
end 


def download_countries 
	require 'open-uri'
	url_country = "http://kayaposoft.com/enrico/json/v1.0/?action=getSupportedCountries"
    countries = JSON.parse(open(url_country).read)
    countries.each do |country|
    	country_name_hash = country["fullName"]
    	country_code_hash = country["countryCode"]
    	Country.create(country_name: country_name_hash, country_code: country_code_hash)    
    end 
end 


# when user click download #
def download_holidays 
   
   require 'open-uri'
   @country = Country.find(params[:id])
   country_code = @country.country_code       
   url_request = "http://kayaposoft.com/enrico/json/v1.0/?action=getPublicHolidaysForYear&year=2013&country=#{country_code}&region="   
   holidays = JSON.parse(open(url_request).read)    
   holidays.each do |holiday|       
      year = holiday["date"]["year"]  
      month = holiday["date"]["month"]
      day = holiday["date"]["day"]
      start_hash  = "#{year}-#{month}-#{day}" 
      title_hash = holiday["englishName"]       
      @country.holidays.create(start_at: start_hash ,name: title_hash)
   end 
    redirect_to country_holidays_path(@country)
    
    if holidays.count > 0 
      @country.update(download: true)
    end 
end 

end 





 

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]
  
  # GET /holidays
  # GET /holidays.json
  def index
    set_country
    #listing all holidays by countries    
    @holidays = @country.holidays
  end
  
  # GET /holidays/1
  # GET /holidays/1.json
  def show
     
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new

  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)
    
    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render action: 'show', status: :created, location: @holiday }
      else
        format.html { render action: 'new' }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url }
      format.json { head :no_content }
    end
  end

  private
    def set_country 
      @country = Country.find(params[:country_id])
    end 

    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def holiday_params
      params[:holiday]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
 # download holiday  and show in details 
  # require object  = country 
  def button_download_show_holidays_for(country)
     if country.holiday_downloaded?  
 	 	 link_to 'Download Holidays', country_holiday_download_path(country), 
 	 	 class: 'btn btn-default'   	 			  
 	 else 
 	 	 link_to 'Show Holidays', country_holidays_path(country), 
 	 	 class: 'btn btn-default'
 	 	 		 
     end 
  end 

end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/application/_nav_bar.html.erb
<div class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path%></li>
        <li><%= link_to "Google", country_path("google")%></li>
        <li><%= link_to "Enrico", country_path("enrico")%></li>
        <li><%= link_to "Daybase", country_path("daybase")%></li>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container --> 
</div>

app/views/countries/index.html.erb
 <h1> Countries Listing </h1>
 	<table class="table table-striped"> 
 	<thead>
 		<tr>
 			<th>No</th>
 			<th>Country Name </th>
 			<th>Country Code </th>
 			<th>Download Holiday</th>
 		</tr>
 	</thead> 
 	<tbody>
 		<% i = 0 %>
 		<% @countries.each do |country|%>  
 			<tr>
 				<td><%= i = i+ 1 %></td>
 				<td><%= country.country_name %></td>
 				<td><%= country.country_code %></td>
 				<td><%= button_download_show_holidays_for country%></td>		
 			</tr>
  		<% end %> 
     </tbody>
 	</table> 
 

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holidays/_form_holiday.html.erb
<h1> Public holidays in <%= @country.country_name %>
<%= link_to "All Countries", countries_path, :class => "btn btn-default pull-right" %> </h1>  

<table class="table table-striped"> 
<thead>
	<th>No</th>
	<th>Name</th>
	<th>Start At</th>
</thead>

<tbody>
	<% i =0%>
	<% @holidays.each do |holiday|%>		
	<tr>
		<td><%= i = i+1 %></td>
		<td><%= holiday.name %></td>
		<td><%= holiday.start_at%></td>
	</tr>
	<% end %>
</tbody>

</table> 

   

app/views/holidays/edit.html.erb
<h1>Editing holiday</h1>

<%= render 'form' %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

app/views/holidays/index.html.erb
<%=render "form_holiday"%>

	

app/views/holidays/new.html.erb
<h1>New holiday</h1>

<%= render 'form' %>

<%= link_to 'Back', holidays_path %>

app/views/holidays/show.html.erb
<%=render "form_holiday"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apitest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render "application/nav_bar"%>
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6"> 
			<%= yield %>		
			</div>	
		<div class="col-md-3"></div>
	</div>



</body>
</html>